/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ui;


import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author erlin
 */
public class Asesor extends javax.swing.JInternalFrame {

    /**
     * Creates new form Acesor
     */
    public Asesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtApellido2Asesor = new javax.swing.JTextField();
        jTxtApellido1Asesor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtNombresAsesor = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jBtnBuscarAsesor = new javax.swing.JButton();
        jBtnGuardarAsesor = new javax.swing.JButton();
        jBtnEliminarAsesor = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jTxtINSSAsesor = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblListarAsesores = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMinimumSize(new java.awt.Dimension(995, 503));
        setPreferredSize(new java.awt.Dimension(995, 503));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nombres");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 70, -1));

        jTxtApellido2Asesor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtApellido2Asesor.setBorder(null);
        jTxtApellido2Asesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApellido2AsesorActionPerformed(evt);
            }
        });
        jTxtApellido2Asesor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtApellido2AsesorKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtApellido2Asesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 150, 20));

        jTxtApellido1Asesor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtApellido1Asesor.setBorder(null);
        jTxtApellido1Asesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtApellido1AsesorActionPerformed(evt);
            }
        });
        jTxtApellido1Asesor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtApellido1AsesorKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtApellido1Asesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 150, 20));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Segundo Apellido");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Codigo INSS");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jTxtNombresAsesor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtNombresAsesor.setBorder(null);
        jTxtNombresAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNombresAsesorActionPerformed(evt);
            }
        });
        jTxtNombresAsesor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtNombresAsesorKeyTyped(evt);
            }
        });
        jPanel2.add(jTxtNombresAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 150, 20));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jBtnBuscarAsesor.setBackground(new java.awt.Color(204, 204, 204));
        jBtnBuscarAsesor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtnBuscarAsesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/buscar.png"))); // NOI18N
        jBtnBuscarAsesor.setText("Buscar");
        jBtnBuscarAsesor.setMaximumSize(new java.awt.Dimension(114, 30));
        jBtnBuscarAsesor.setMinimumSize(new java.awt.Dimension(114, 30));
        jBtnBuscarAsesor.setPreferredSize(new java.awt.Dimension(114, 30));
        jBtnBuscarAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarAsesorActionPerformed(evt);
            }
        });

        jBtnGuardarAsesor.setBackground(new java.awt.Color(204, 204, 204));
        jBtnGuardarAsesor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtnGuardarAsesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save_icon-icons.com_73702.png"))); // NOI18N
        jBtnGuardarAsesor.setText("Guardar");
        jBtnGuardarAsesor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnGuardarAsesor.setMaximumSize(new java.awt.Dimension(114, 30));
        jBtnGuardarAsesor.setMinimumSize(new java.awt.Dimension(114, 30));
        jBtnGuardarAsesor.setPreferredSize(new java.awt.Dimension(114, 30));
        jBtnGuardarAsesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnGuardarAsesorMouseEntered(evt);
            }
        });
        jBtnGuardarAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarAsesorActionPerformed(evt);
            }
        });

        jBtnEliminarAsesor.setBackground(new java.awt.Color(204, 204, 204));
        jBtnEliminarAsesor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtnEliminarAsesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eliminar.png"))); // NOI18N
        jBtnEliminarAsesor.setText("Eliminar");
        jBtnEliminarAsesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnEliminarAsesorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnEliminarAsesorMouseExited(evt);
            }
        });
        jBtnEliminarAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarAsesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jBtnGuardarAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnBuscarAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jBtnEliminarAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEliminarAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnBuscarAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnGuardarAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 410, 70));

        jLabel9.setFont(new java.awt.Font("Centaur", 3, 14)); // NOI18N
        jLabel9.setText("¡A la libertad por la Universidad!");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 190, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logo Departamento.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 240, 50));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 150, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 150, -1));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 150, -1));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 150, -1));

        jTxtINSSAsesor.setBorder(null);
        try {
            jTxtINSSAsesor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTxtINSSAsesor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtINSSAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtINSSAsesorActionPerformed(evt);
            }
        });
        jPanel2.add(jTxtINSSAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 150, 20));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Datos Asesor");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 120, -1));

        jTblListarAsesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo Inss", "Nombres", "Apellidos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTblListarAsesores.setFocusable(false);
        jTblListarAsesores.setGridColor(new java.awt.Color(0, 0, 0));
        jTblListarAsesores.setRowHeight(25);
        jTblListarAsesores.setSelectionBackground(new java.awt.Color(0, 51, 102));
        jTblListarAsesores.setShowHorizontalLines(true);
        jTblListarAsesores.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTblListarAsesores);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, 450, 340));

        jPanel1.setBackground(new java.awt.Color(245, 211, 17));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(225, 24));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setText("Listado de asesores");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(155, 155, 155))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 450, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Primer Apellido");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtApellido2AsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApellido2AsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApellido2AsesorActionPerformed

    private void jTxtApellido2AsesorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtApellido2AsesorKeyTyped
        // TODO add your handling code here:
        char validar =  evt.getKeyChar();
        if (Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTxtApellido2AsesorKeyTyped

    private void jTxtApellido1AsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtApellido1AsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtApellido1AsesorActionPerformed

    private void jTxtApellido1AsesorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtApellido1AsesorKeyTyped
        char validar =  evt.getKeyChar();
        if (Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTxtApellido1AsesorKeyTyped

    private void jTxtNombresAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNombresAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNombresAsesorActionPerformed

    private void jTxtNombresAsesorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNombresAsesorKeyTyped
        char validar =  evt.getKeyChar();
        if (Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTxtNombresAsesorKeyTyped

    private void jBtnBuscarAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarAsesorActionPerformed
        /*try {
            // Preparar los datos que se guardaran del tecnico:
            //ResultSet rst = Ctr_Tutor.buscar(this.jTxtINSS.getText());
            String inss = this.jTxtINSS.getText();
            String sql = "SELECT * FROM Tutor";
            cnx.

            if (rst > 0) {
                JOptionPane.showMessageDialog(this, "Registro grabado con exito"
                    , "Grabar Registro", JOptionPane.INFORMATION_MESSAGE);
            }//Fin de la instrucción if
        } catch(Exception ex){

        }*/
    }//GEN-LAST:event_jBtnBuscarAsesorActionPerformed

    private void jBtnGuardarAsesorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnGuardarAsesorMouseEntered

    }//GEN-LAST:event_jBtnGuardarAsesorMouseEntered

    private void jBtnGuardarAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarAsesorActionPerformed

    }//GEN-LAST:event_jBtnGuardarAsesorActionPerformed

    private void jBtnEliminarAsesorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEliminarAsesorMouseEntered
        jBtnEliminarAsesor.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_jBtnEliminarAsesorMouseEntered

    private void jBtnEliminarAsesorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEliminarAsesorMouseExited
        jBtnEliminarAsesor.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_jBtnEliminarAsesorMouseExited

    private void jBtnEliminarAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEliminarAsesorActionPerformed

    private void jTxtINSSAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtINSSAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtINSSAsesorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscarAsesor;
    private javax.swing.JButton jBtnEliminarAsesor;
    private javax.swing.JButton jBtnGuardarAsesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTblListarAsesores;
    private javax.swing.JTextField jTxtApellido1Asesor;
    private javax.swing.JTextField jTxtApellido2Asesor;
    private javax.swing.JFormattedTextField jTxtINSSAsesor;
    private javax.swing.JTextField jTxtNombresAsesor;
    // End of variables declaration//GEN-END:variables
}
