/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ui;

import java.awt.Color;

/**
 *
 * @author Dell Latitude 7490
 */
public class Carrera extends javax.swing.JInternalFrame {

    /**
     * Creates new form Estatico
     */
    public Carrera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblListarCarrera = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jBtnBuscarCar = new javax.swing.JButton();
        jBtnGuardarCar = new javax.swing.JButton();
        jBtnEliminarCar = new javax.swing.JButton();
        jTxtDescripcionCarrera = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jTxtCodigoCarrera = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximumSize(new java.awt.Dimension(841, 437));
        setPreferredSize(new java.awt.Dimension(841, 437));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logo Departamento.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 354, -1, -1));

        jLabel13.setFont(new java.awt.Font("Centaur", 3, 14)); // NOI18N
        jLabel13.setText("¡A la libertad por la Universidad!");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 368, 190, 20));

        jPanel4.setBackground(new java.awt.Color(51, 0, 102));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro Carrera");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(342, 342, 342))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Codigo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 103, 150, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Descripción");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        jPanel2.setBackground(new java.awt.Color(245, 211, 17));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(225, 24));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setText("Listado de carreras ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(147, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(115, 115, 115))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 60, 397, 20));

        jTblListarCarrera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTblListarCarrera.setFocusable(false);
        jTblListarCarrera.setGridColor(new java.awt.Color(0, 0, 0));
        jTblListarCarrera.setRowHeight(25);
        jTblListarCarrera.setSelectionBackground(new java.awt.Color(0, 51, 102));
        jTblListarCarrera.setShowHorizontalLines(true);
        jTblListarCarrera.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTblListarCarrera);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 81, 397, 136));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jBtnBuscarCar.setBackground(new java.awt.Color(204, 204, 204));
        jBtnBuscarCar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtnBuscarCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/buscar.png"))); // NOI18N
        jBtnBuscarCar.setText("Buscar");
        jBtnBuscarCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarCarActionPerformed(evt);
            }
        });

        jBtnGuardarCar.setBackground(new java.awt.Color(204, 204, 204));
        jBtnGuardarCar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtnGuardarCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save_icon-icons.com_73702.png"))); // NOI18N
        jBtnGuardarCar.setText("Guardar");
        jBtnGuardarCar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnGuardarCar.setMaximumSize(new java.awt.Dimension(107, 30));
        jBtnGuardarCar.setMinimumSize(new java.awt.Dimension(107, 30));
        jBtnGuardarCar.setPreferredSize(new java.awt.Dimension(107, 30));
        jBtnGuardarCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarCarActionPerformed(evt);
            }
        });

        jBtnEliminarCar.setBackground(new java.awt.Color(204, 204, 204));
        jBtnEliminarCar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtnEliminarCar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eliminar.png"))); // NOI18N
        jBtnEliminarCar.setText("Eliminar");
        jBtnEliminarCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBtnEliminarCarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBtnEliminarCarMouseExited(evt);
            }
        });
        jBtnEliminarCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarCarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jBtnGuardarCar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnBuscarCar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jBtnEliminarCar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEliminarCar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnBuscarCar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnGuardarCar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 155, -1, -1));

        jTxtDescripcionCarrera.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTxtDescripcionCarrera.setBorder(null);
        jTxtDescripcionCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDescripcionCarreraActionPerformed(evt);
            }
        });
        jTxtDescripcionCarrera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtDescripcionCarreraKeyTyped(evt);
            }
        });
        jPanel1.add(jTxtDescripcionCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 83, 150, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 103, 150, -1));

        jTxtCodigoCarrera.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTxtCodigoCarrera.setBorder(null);
        jTxtCodigoCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoCarreraActionPerformed(evt);
            }
        });
        jTxtCodigoCarrera.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCodigoCarreraKeyTyped(evt);
            }
        });
        jPanel1.add(jTxtCodigoCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 83, 150, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBuscarCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarCarActionPerformed
        /*try {
            // Preparar los datos que se guardaran del tecnico:
            //ResultSet rst = Ctr_Tutor.buscar(this.jTxtINSS.getText());
            String inss = this.jTxtINSS.getText();
            String sql = "SELECT * FROM Tutor";
            cnx.

            if (rst > 0) {
                JOptionPane.showMessageDialog(this, "Registro grabado con exito"
                    , "Grabar Registro", JOptionPane.INFORMATION_MESSAGE);
            }//Fin de la instrucción if
        } catch(Exception ex){

        }*/
    }//GEN-LAST:event_jBtnBuscarCarActionPerformed

    private void jBtnGuardarCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarCarActionPerformed

    }//GEN-LAST:event_jBtnGuardarCarActionPerformed

    private void jBtnEliminarCarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEliminarCarMouseEntered
        jBtnEliminarCar.setBackground(new Color(255,0,0));
    }//GEN-LAST:event_jBtnEliminarCarMouseEntered

    private void jBtnEliminarCarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnEliminarCarMouseExited
        jBtnEliminarCar.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_jBtnEliminarCarMouseExited

    private void jBtnEliminarCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnEliminarCarActionPerformed

    private void jTxtDescripcionCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDescripcionCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDescripcionCarreraActionPerformed

    private void jTxtDescripcionCarreraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtDescripcionCarreraKeyTyped
        char validar =  evt.getKeyChar();
        if (Character.isDigit(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTxtDescripcionCarreraKeyTyped

    private void jTxtCodigoCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoCarreraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigoCarreraActionPerformed

    private void jTxtCodigoCarreraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCodigoCarreraKeyTyped
        // TODO add your handling code here:
         if (jTxtCodigoCarrera.getText().length() > 8)
            evt.consume();
    }//GEN-LAST:event_jTxtCodigoCarreraKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscarCar;
    private javax.swing.JButton jBtnEliminarCar;
    private javax.swing.JButton jBtnGuardarCar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTblListarCarrera;
    private javax.swing.JTextField jTxtCodigoCarrera;
    private javax.swing.JTextField jTxtDescripcionCarrera;
    // End of variables declaration//GEN-END:variables
}
