/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ui;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import servicios.MS_SQLServer;
import servicios.ValidacionDatos;

/**
 *
 * @author lnarvaezb
 */
public class Conf_Server extends javax.swing.JInternalFrame {

    /**
     * Creates new form Conf_Server
     */
    public Conf_Server() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtServerName = new javax.swing.JTextField();
        jTxtDateBase = new javax.swing.JTextField();
        jCmbTypeServer = new javax.swing.JComboBox<>();
        jTxtPort = new javax.swing.JTextField();
        jTxtUser = new javax.swing.JTextField();
        jPswPassword = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBtn_closed = new javax.swing.JButton();
        jBtn__Guardar = new javax.swing.JButton();
        jBrnHelp = new javax.swing.JButton();
        jBtnTestCnx = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setIconifiable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Nombre del Servidor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jTxtServerName.setToolTipText("Indicar el nombre de servidor");
        jTxtServerName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtServerNameMouseClicked(evt);
            }
        });
        jTxtServerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtServerNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTxtServerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 228, 26));

        jTxtDateBase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtDateBaseMouseClicked(evt);
            }
        });
        jPanel1.add(jTxtDateBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 228, 26));

        jCmbTypeServer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "MS-SQL Server", "MySQL", "PostgreSQL" }));
        jPanel1.add(jCmbTypeServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 228, 26));

        jTxtPort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtPortMouseClicked(evt);
            }
        });
        jPanel1.add(jTxtPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 228, 26));

        jTxtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtUserMouseClicked(evt);
            }
        });
        jPanel1.add(jTxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 228, 26));

        jPswPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPswPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(jPswPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 228, 26));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Contraseña");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Usuario");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Puerto");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Tipo Servidor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Base de Datos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Configurar Servidor");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 205, -1));

        jBtn_closed.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtn_closed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cerrar-sesion.png"))); // NOI18N
        jBtn_closed.setText("Cerrar");
        jBtn_closed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtn_closed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_closedActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn_closed, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 180, 40));

        jBtn__Guardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtn__Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save_icon-icons.com_73702.png"))); // NOI18N
        jBtn__Guardar.setText("Guardar");
        jBtn__Guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtn__Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn__GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jBtn__Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 180, -1));

        jBrnHelp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBrnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/question.png"))); // NOI18N
        jBrnHelp.setText("Ayuda");
        jBrnHelp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jBrnHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 180, 40));

        jBtnTestCnx.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtnTestCnx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/worldwide (1).png"))); // NOI18N
        jBtnTestCnx.setText("Probar Conexión");
        jBtnTestCnx.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnTestCnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTestCnxActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnTestCnx, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 180, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logo Departamento.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 240, 50));

        jLabel9.setFont(new java.awt.Font("Centaur", 3, 14)); // NOI18N
        jLabel9.setText("¡A la libertad por la Universidad!");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 190, 20));

        jLabel11.setFont(new java.awt.Font("Centaur", 3, 14)); // NOI18N
        jLabel11.setText("¡A la libertad por la Universidad!");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 190, 20));

        jLabel12.setFont(new java.awt.Font("Centaur", 3, 14)); // NOI18N
        jLabel12.setText("¡A la libertad por la Universidad!");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 190, 20));

        jLabel8.setFont(new java.awt.Font("Centaur", 3, 14)); // NOI18N
        jLabel8.setText("¡A la libertad por la Universidad!");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_closedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_closedActionPerformed
        // TODO add your handling code here:
        this.dispose(); //Cerrar la ventana
    }//GEN-LAST:event_jBtn_closedActionPerformed
    /**
     * Busca establecer la conexión con el servidor de bases de datos indicado 
     * los datos de configuración
     * @param evt manejador para determinar el evento
     */
    private void jBtn__GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn__GuardarActionPerformed
        
    }//GEN-LAST:event_jBtn__GuardarActionPerformed
    
    private void jTxtServerNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtServerNameMouseClicked
        // TODO add your handling code here:        
        this.jTxtServerName.setBackground(Color.WHITE);        
    }//GEN-LAST:event_jTxtServerNameMouseClicked

    private void jBtnTestCnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTestCnxActionPerformed
        // TODO add your handling code here:
        try {            
             if (ValidacionCampos ()){
                MS_SQLServer con = new MS_SQLServer ();
                JOptionPane.showMessageDialog(rootPane, "Estamos Bien, un exito"); 
             }//Fin de la instrucción if
             else {
                 JOptionPane.showMessageDialog(this, "Existen campos que no han"
                                      + " sido completados o estan incorrectos", 
                                "Error en Captura de Datos", JOptionPane.ERROR_MESSAGE);
             }//Fin else
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Clase no encontrada:" 
                        + ex.getMessage() + "\n", "Error de Librería"
                        , JOptionPane.ERROR_MESSAGE);
        } catch (InstantiationException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error de instancia: " 
                        + ex.getMessage() + "\n", "Error de Librería"
                        , JOptionPane.ERROR_MESSAGE);
        } catch (IllegalAccessException ex) {
                JOptionPane.showMessageDialog(rootPane, "Acceso Ilegal: " 
                        + ex.getMessage() + "\n", "Error de Acceso"
                        , JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Acceso Ilegal: " 
                        + ex.getMessage() + "\n", "Error SQLException"
                        , JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnTestCnxActionPerformed

    private void jTxtDateBaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtDateBaseMouseClicked
        // TODO add your handling code here:
        this.jTxtDateBase.setBackground(Color.WHITE); 
    }//GEN-LAST:event_jTxtDateBaseMouseClicked

    private void jTxtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtUserMouseClicked
        // TODO add your handling code here:
        this.jTxtUser.setBackground(Color.WHITE); 
    }//GEN-LAST:event_jTxtUserMouseClicked

    private void jPswPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPswPasswordMouseClicked
        // TODO add your handling code here:
        this.jPswPassword.setBackground(Color.WHITE); 
    }//GEN-LAST:event_jPswPasswordMouseClicked

    private void jTxtPortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtPortMouseClicked
        // TODO add your handling code here:
        this.jTxtPort.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTxtPortMouseClicked

    private void jTxtServerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtServerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtServerNameActionPerformed
    
    private boolean ValidacionCampos () {
        boolean valido =true;        
        if (!ValidacionDatos.isTextFieldValid(jTxtServerName, 
                                             jTxtServerName.getText(),8, 128))
            valido = false;
        //Validar en el campo nombre de base de datos
        if (!ValidacionDatos.isTextFieldValid(jTxtDateBase, 
                                             jTxtDateBase.getText(),6, 64))
            valido = false;
        //Validar en el campo número de puerto para conexion
        if (!ValidacionDatos.isNumValido(jTxtPort))
            valido = false;
        //Validar en el campo nombre de usuario para la conexión
        if (!ValidacionDatos.isTextFieldValid(jTxtUser,
                                             jTxtUser.getText(), 4, 64))
            valido = false;
        //Validar en el campo clave de usuario que tenga datos
        if (this.jPswPassword.getPassword().length < 6 || 
            this.jPswPassword.getPassword().length > 24)
        {
            this.jPswPassword.setBackground(Color.red);
            return false;
        }
        //Regresar verdadero si se han superado las validaciones
        return valido;
    }//Fin de validación
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBrnHelp;
    private javax.swing.JButton jBtnTestCnx;
    private javax.swing.JButton jBtn__Guardar;
    private javax.swing.JButton jBtn_closed;
    private javax.swing.JComboBox<String> jCmbTypeServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPswPassword;
    private javax.swing.JTextField jTxtDateBase;
    private javax.swing.JTextField jTxtPort;
    private javax.swing.JTextField jTxtServerName;
    private javax.swing.JTextField jTxtUser;
    // End of variables declaration//GEN-END:variables
}
