package ui;

import controlador.CtrlConsultas;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author erlin
 */
public class Consultas extends javax.swing.JInternalFrame {

    String[] fila3 = {"Carrera", "Modalidad", "Titulo", "Fecha Defensa", "Resumen"};
    
    DefaultTableModel dmt1 = new DefaultTableModel();
    
    
    public Consultas() {
        initComponents();
        jPnlFiltro.setVisible(false);
        dmt1.addColumn("Carrera");
        dmt1.addColumn("Modalidad");
        dmt1.addColumn("Titulo Trabajo");
        dmt1.addColumn("Fecha");
        dmt1.addColumn("Resumen");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPnlFiltro = new javax.swing.JPanel();
        jCmbCarreraCon = new javax.swing.JComboBox<>();
        jCmbModalidadCON = new javax.swing.JComboBox<>();
        jCmbSemestreCON = new javax.swing.JComboBox<>();
        jChkProtocolosCon = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblListarTutor = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPnlAnimacion = new javax.swing.JPanel();
        jLTitulo = new javax.swing.JLabel();
        jTxtBarraBusqueda = new java.awt.TextField();
        jBtnBuscarConsu = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setMaximumSize(new java.awt.Dimension(1239, 594));
        setPreferredSize(new java.awt.Dimension(1239, 594));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1171, 93, -1, -1));

        jPnlFiltro.setBackground(new java.awt.Color(255, 255, 255));
        jPnlFiltro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPnlFiltroMouseEntered(evt);
            }
        });

        jCmbCarreraCon.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCmbCarreraCon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carrera", " " }));

        jCmbModalidadCON.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCmbModalidadCON.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Modalidad Graduacion", " " }));

        jCmbSemestreCON.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jCmbSemestreCON.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semestre", "Semestre 1", "Semestre 2", " " }));

        jChkProtocolosCon.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jChkProtocolosCon.setText("Protocolos");

        javax.swing.GroupLayout jPnlFiltroLayout = new javax.swing.GroupLayout(jPnlFiltro);
        jPnlFiltro.setLayout(jPnlFiltroLayout);
        jPnlFiltroLayout.setHorizontalGroup(
            jPnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlFiltroLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jCmbCarreraCon, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCmbModalidadCON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCmbSemestreCON, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChkProtocolosCon)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPnlFiltroLayout.setVerticalGroup(
            jPnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlFiltroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnlFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbCarreraCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmbModalidadCON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmbSemestreCON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkProtocolosCon))
                .addGap(68, 68, 68))
        );

        jPanel2.add(jPnlFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 118, -1, 34));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jPanel1MouseWheelMoved(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/filter.png"))); // NOI18N
        jLabel1.setText("Filtro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 64, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Consultas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(566, 566, 566)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(582, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTblListarTutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carrera", "Modalidad", "Titulo trabajo", "Fecha", "Resumen trabajo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblListarTutor.setFocusable(false);
        jTblListarTutor.setGridColor(new java.awt.Color(0, 0, 0));
        jTblListarTutor.setRowHeight(25);
        jTblListarTutor.setSelectionBackground(new java.awt.Color(0, 51, 102));
        jTblListarTutor.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTblListarTutor);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 194, 1146, 270));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logo Departamento.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 490, -1, -1));

        jLabel9.setFont(new java.awt.Font("Centaur", 3, 14)); // NOI18N
        jLabel9.setText("¡A la libertad por la Universidad!");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1025, 512, 190, 20));

        jPnlAnimacion.setBackground(new java.awt.Color(255, 255, 255));

        jLTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLTitulo.setText("Titulo");

        jBtnBuscarConsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/buscar.png"))); // NOI18N
        jBtnBuscarConsu.setText("Buscar");
        jBtnBuscarConsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarConsuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlAnimacionLayout = new javax.swing.GroupLayout(jPnlAnimacion);
        jPnlAnimacion.setLayout(jPnlAnimacionLayout);
        jPnlAnimacionLayout.setHorizontalGroup(
            jPnlAnimacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAnimacionLayout.createSequentialGroup()
                .addComponent(jLTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtBarraBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jBtnBuscarConsu)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        jPnlAnimacionLayout.setVerticalGroup(
            jPnlAnimacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlAnimacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnlAnimacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnBuscarConsu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtBarraBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jPanel2.add(jPnlAnimacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 560, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jPanel1MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseWheelMoved

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        
       
        
        if(jPnlFiltro.isVisible()){
        
            jPnlFiltro.setVisible(false);
      
        }
        else {
            jPnlFiltro.setVisible(true);
           
        }
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseExited

    private void jPnlFiltroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPnlFiltroMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPnlFiltroMouseEntered

    private void jBtnBuscarConsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarConsuActionPerformed
        // Realizar consultas
        try {
            //1. Cargar la lista de Facultades
            /*for (String trabajo : CtrlConsultas.listaPorTitulo(jTxtBarraBusqueda.getText())) {
                String[] datos = trabajo.split(",");
                dmt1.addRow(datos);
                
            }//Fin de for
            jTblListarTutor.setModel(dmt1);*/
            this.limpiar();
            CtrlConsultas.listar(jTblListarTutor, this.jTxtBarraBusqueda.getText());

            //2. Cargar la lista de departamentos
            //for (negocio.Tutor tut : CtrlTutor.listar()) {
            //    this.jCmbTutorSemi.addItem(tut.getNombre() + " " + tut.getP_apellido());
            //}//Fin for departamentos            
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Se ha producido una falla"
                    + " al tratar de listar los registros solicitados \n "
                    + "\n " + ex, "Error al cargar "
                    + "listado", JOptionPane.ERROR_MESSAGE);
        }
        
        
        /*catch (ClassNotFoundException | InstantiationException
                | IllegalAccessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Se ha producido una falla"
                    + " al tratar de listar Facultades y Departamentos \n "
                    + " registrados actualmente", "Error al cargar"
                    + "listado", JOptionPane.ERROR_MESSAGE);
        }*/
    }//GEN-LAST:event_jBtnBuscarConsuActionPerformed

    // Metodo para limpiar tabla
    private void limpiar(){
        DefaultTableModel tb = (DefaultTableModel) jTblListarTutor.getModel();
        tb.setRowCount(0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBuscarConsu;
    private javax.swing.JCheckBox jChkProtocolosCon;
    private javax.swing.JComboBox<String> jCmbCarreraCon;
    private javax.swing.JComboBox<String> jCmbModalidadCON;
    private javax.swing.JComboBox<String> jCmbSemestreCON;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPnlAnimacion;
    private javax.swing.JPanel jPnlFiltro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblListarTutor;
    private java.awt.TextField jTxtBarraBusqueda;
    // End of variables declaration//GEN-END:variables
}
