/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ui;

/**
 *
 * @author Dell Latitude 7490
 */
public class RegistroAdmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroAdmin
     */
    public RegistroAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JbtnSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtCorreo = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPswConfirmacion = new javax.swing.JPasswordField();
        jPswContrasenia = new javax.swing.JPasswordField();
        jBtnGuardarAdmi = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMinimumSize(new java.awt.Dimension(660, 350));
        setPreferredSize(new java.awt.Dimension(660, 350));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JbtnSesion.setBackground(new java.awt.Color(204, 204, 204));
        JbtnSesion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JbtnSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/account.png"))); // NOI18N
        JbtnSesion.setText("Iniciar Sesión");
        JbtnSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnSesionActionPerformed(evt);
            }
        });
        jPanel1.add(JbtnSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 150, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Registro Administrador");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 160, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Correo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 70, -1));

        jTxtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtCorreo.setBorder(null);
        jTxtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCorreoActionPerformed(evt);
            }
        });
        jTxtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtCorreoKeyTyped(evt);
            }
        });
        jPanel1.add(jTxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 150, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 150, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Confirmar contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 150, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 150, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logo Departamento.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, 40));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 150, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Contraseña");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 90, 20));

        jLabel9.setFont(new java.awt.Font("Centaur", 3, 14)); // NOI18N
        jLabel9.setText("¡A la libertad por la Universidad!");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 190, 20));

        jPswConfirmacion.setBorder(null);
        jPanel1.add(jPswConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 150, 20));

        jPswContrasenia.setBorder(null);
        jPanel1.add(jPswContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 150, 20));

        jBtnGuardarAdmi.setBackground(new java.awt.Color(204, 204, 204));
        jBtnGuardarAdmi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jBtnGuardarAdmi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/register (1).png"))); // NOI18N
        jBtnGuardarAdmi.setText("Guardar");
        jBtnGuardarAdmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarAdmiActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnGuardarAdmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCorreoActionPerformed

    private void jTxtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtCorreoKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTxtCorreoKeyTyped

    private void JbtnSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnSesionActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        Sistema_UI.dskPanelMDI.add(login);
        login.toFront();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JbtnSesionActionPerformed

    private void jBtnGuardarAdmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarAdmiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnGuardarAdmiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnSesion;
    private javax.swing.JButton jBtnGuardarAdmi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPswConfirmacion;
    private javax.swing.JPasswordField jPswContrasenia;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTxtCorreo;
    // End of variables declaration//GEN-END:variables
}
