package ui;

import controlador.CtrlCarrera;
import controlador.CtrlEstudiante;
import controlador.CtrlSeminario;
import controlador.CtrlTutor;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import negocio.Estudiante;

public class Seminario extends javax.swing.JInternalFrame {

    //Recuperación de los ID de los registros a insertar
    private int idTutor;   //Variable para almacenar los id de los Tutores
    private int idModalidad;   //Variable para almacenar el id de la modalidad
    private int idCarrera; //Variable para almacenar los id de la carrera
    private int idEst_1;  //Variable que almacenará al estudiante
    private int idEst_2;  //Variable que almacenará al estudiante
    private int idEst_3;  //Variable que almacenará al estudiante

    public Seminario() {
        idTutor = 0;
        idModalidad = 0;
        idCarrera = 0;
        idEst_1 = 0;
        idEst_2 = 0;
        idEst_3 = 0;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jBtnBorrarSemi = new javax.swing.JButton();
        jBtnGuardarSemi = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jTxtAutor2Semi = new javax.swing.JTextField();
        jTxtAutor1Semi = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jTxtAutor3Semi = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jBtnBuscarAutSemi2 = new javax.swing.JButton();
        jBtnBuscarAutSemi1 = new javax.swing.JButton();
        jBtnBuscarAutSemi3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jCmbCarreraSemi = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCmbSemestreSemi = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTxtTutorNombre = new javax.swing.JTextField();
        jBtnBuscarTutor = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtTemaSemi = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jTxtResumenSemi = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jBtnExaminarSemi = new javax.swing.JButton();
        jDtChFechaSeminario = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setFrameIcon(null);
        setMaximumSize(new java.awt.Dimension(1218, 494));
        setMinimumSize(new java.awt.Dimension(320, 260));
        setPreferredSize(new java.awt.Dimension(1218, 494));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jBtnBorrarSemi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtnBorrarSemi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eliminar.png"))); // NOI18N
        jBtnBorrarSemi.setText("Anular");
        jBtnBorrarSemi.setMaximumSize(new java.awt.Dimension(1280, 650));
        jBtnBorrarSemi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBorrarSemiActionPerformed(evt);
            }
        });

        jBtnGuardarSemi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBtnGuardarSemi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save_icon-icons.com_73702.png"))); // NOI18N
        jBtnGuardarSemi.setText("Registrar");
        jBtnGuardarSemi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarSemiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnGuardarSemi)
                .addGap(18, 18, 18)
                .addComponent(jBtnBorrarSemi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnGuardarSemi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnBorrarSemi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 370, 80));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Autores"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 47, 266, -1));

        jTxtAutor2Semi.setEditable(false);
        jTxtAutor2Semi.setBorder(null);
        jTxtAutor2Semi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAutor2SemiActionPerformed(evt);
            }
        });
        jPanel5.add(jTxtAutor2Semi, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 72, 266, 19));

        jTxtAutor1Semi.setEditable(false);
        jTxtAutor1Semi.setBorder(null);
        jTxtAutor1Semi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAutor1SemiActionPerformed(evt);
            }
        });
        jPanel5.add(jTxtAutor1Semi, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 30, 266, 19));
        jPanel5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 266, -1));

        jTxtAutor3Semi.setEditable(false);
        jTxtAutor3Semi.setBorder(null);
        jTxtAutor3Semi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAutor3SemiActionPerformed(evt);
            }
        });
        jPanel5.add(jTxtAutor3Semi, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 112, 266, 19));
        jPanel5.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 266, -1));

        jBtnBuscarAutSemi2.setBackground(new java.awt.Color(204, 204, 204));
        jBtnBuscarAutSemi2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/a-la-vista.png"))); // NOI18N
        jBtnBuscarAutSemi2.setText("Buscar");
        jBtnBuscarAutSemi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarAutSemi2ActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnBuscarAutSemi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 65, 107, -1));

        jBtnBuscarAutSemi1.setBackground(new java.awt.Color(204, 204, 204));
        jBtnBuscarAutSemi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/a-la-vista.png"))); // NOI18N
        jBtnBuscarAutSemi1.setText("Buscar");
        jBtnBuscarAutSemi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarAutSemi1ActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnBuscarAutSemi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 24, 107, -1));

        jBtnBuscarAutSemi3.setBackground(new java.awt.Color(204, 204, 204));
        jBtnBuscarAutSemi3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/a-la-vista.png"))); // NOI18N
        jBtnBuscarAutSemi3.setText("Buscar");
        jBtnBuscarAutSemi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarAutSemi3ActionPerformed(evt);
            }
        });
        jPanel5.add(jBtnBuscarAutSemi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 106, 107, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 420, 150));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jCmbCarreraSemi.setBackground(new java.awt.Color(204, 204, 204));
        jCmbCarreraSemi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        jCmbCarreraSemi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbCarreraSemiItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Carrera");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Semestre");

        jCmbSemestreSemi.setBackground(new java.awt.Color(204, 204, 204));
        jCmbSemestreSemi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "1", "2" }));
        jCmbSemestreSemi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbSemestreSemiActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Tutor");

        jTxtTutorNombre.setEditable(false);
        jTxtTutorNombre.setBorder(null);
        jTxtTutorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTutorNombreActionPerformed(evt);
            }
        });

        jBtnBuscarTutor.setBackground(new java.awt.Color(204, 204, 204));
        jBtnBuscarTutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/a-la-vista.png"))); // NOI18N
        jBtnBuscarTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarTutorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtTutorNombre)
                            .addComponent(jSeparator2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnBuscarTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jCmbSemestreSemi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCmbCarreraSemi, 0, 233, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jBtnBuscarTutor)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jTxtTutorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbCarreraSemi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbSemestreSemi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 370, 150));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Tema");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Resumen");

        jTxtTemaSemi.setBorder(null);
        jTxtTemaSemi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTemaSemiActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Fecha");

        jTxtResumenSemi.setBorder(null);
        jTxtResumenSemi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtResumenSemiActionPerformed(evt);
            }
        });

        jBtnExaminarSemi.setBackground(new java.awt.Color(204, 204, 204));
        jBtnExaminarSemi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder.png"))); // NOI18N
        jBtnExaminarSemi.setText("Examinar");
        jBtnExaminarSemi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExaminarSemiActionPerformed(evt);
            }
        });

        jDtChFechaSeminario.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jTxtResumenSemi)
                                .addGap(8, 8, 8))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jDtChFechaSeminario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTxtTemaSemi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnExaminarSemi)
                .addGap(123, 123, 123))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTxtTemaSemi, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGap(5, 5, 5)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jDtChFechaSeminario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jTxtResumenSemi, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jBtnExaminarSemi)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 400, 180));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Logo Departamento.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 240, 50));

        jLabel13.setFont(new java.awt.Font("Centaur", 3, 14)); // NOI18N
        jLabel13.setText("¡A la libertad por la Universidad!");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 430, 190, 20));

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Registro de seminarios");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1220, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1240, 480));

        setBounds(0, 0, 1218, 494);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBorrarSemiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBorrarSemiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnBorrarSemiActionPerformed

    private void jTxtAutor2SemiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAutor2SemiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAutor2SemiActionPerformed

    private void jTxtAutor1SemiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAutor1SemiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAutor1SemiActionPerformed

    private void jTxtAutor3SemiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAutor3SemiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAutor3SemiActionPerformed

    private void jTxtTemaSemiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTemaSemiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTemaSemiActionPerformed

    private void jTxtResumenSemiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtResumenSemiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtResumenSemiActionPerformed

    private void jBtnBuscarAutSemi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarAutSemi2ActionPerformed
        // Buscar al segundo estudiante
        String carnet = JOptionPane.showInputDialog(this, "Digite "
                + "número de Carnet del Estudiante",
                "Tutor a Buscar", JOptionPane.INFORMATION_MESSAGE);
        //Buscar el alumno con su carnet
        try {
            negocio.Estudiante es = CtrlEstudiante.leerRegistro(carnet);

            // Si el resultado no es NULL, entonces recuperamos el registro
            if (es != null) {
                //Recuperar el Id que se mandará a relacionar
                idEst_2 = es.getIdEst();
                this.jTxtAutor2Semi.setText(es.getNombre() + " " + es.getP_apellido()
                        + " " + es.getS_apellido());
            }

        } catch (ClassNotFoundException | InstantiationException
                | IllegalAccessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "No se ha podido"
                    + " identificar al tutor \n " + ex.getMessage()
                    + " indicado por número de INSS",
                    "Registro no encontrado"
                    + "listado", JOptionPane.ERROR_MESSAGE);
        }//Fin
    }//GEN-LAST:event_jBtnBuscarAutSemi2ActionPerformed

    private void jBtnBuscarAutSemi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarAutSemi1ActionPerformed
        // Buscar al primer estudiante
        String carnet = JOptionPane.showInputDialog(this, "Digite "
                + "número de Carnet del Estudiante",
                "Tutor a Buscar", JOptionPane.INFORMATION_MESSAGE);
        //Buscar el Tutor de acuerdo al corre electrónco especificado
        try {
            negocio.Estudiante es = CtrlEstudiante.leerRegistro(carnet);

            // Si el resultado no es NULL, entonces recuperamos el registro
            if (es != null) {
                //Recuperar el Id que se mandará a relacionar
                idEst_1 = es.getIdEst();
                this.jTxtAutor1Semi.setText(es.getNombre() + " " + es.getP_apellido()
                        + " " + es.getS_apellido());
            }

        } catch (ClassNotFoundException | InstantiationException
                | IllegalAccessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "No se ha podido"
                    + " identificar al tutor \n " + ex.getMessage()
                    + " indicado por número de INSS",
                    "Registro no encontrado"
                    + "listado", JOptionPane.ERROR_MESSAGE);
        }//Fin
    }//GEN-LAST:event_jBtnBuscarAutSemi1ActionPerformed

    private void jBtnBuscarAutSemi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarAutSemi3ActionPerformed
        // Buscar al tercer estudiante
        String carnet = JOptionPane.showInputDialog(this, "Digite "
                + "número de Carnet del Estudiante",
                "Tutor a Buscar", JOptionPane.INFORMATION_MESSAGE);
        //Buscar el Tutor de acuerdo al corre electrónco especificado
        try {
            negocio.Estudiante es = CtrlEstudiante.leerRegistro(carnet);

            // Si el resultado no es NULL, recuperamos el registro
            if (es != null) {
                //Recuperar el Id que se mandará a relacionar
                idEst_3 = es.getIdEst();
                this.jTxtAutor3Semi.setText(es.getNombre() + " " + es.getP_apellido()
                        + " " + es.getS_apellido());
            }

        } catch (ClassNotFoundException | InstantiationException
                | IllegalAccessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "No se ha podido"
                    + " identificar al tutor \n " + ex.getMessage()
                    + " indicado por número de INSS",
                    "Registro no encontrado"
                    + "listado", JOptionPane.ERROR_MESSAGE);
        }//Fin
    }//GEN-LAST:event_jBtnBuscarAutSemi3ActionPerformed

    private void jCmbSemestreSemiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbSemestreSemiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbSemestreSemiActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // Rellenar los combobox
        try {
            //1. Cargar la lista de Facultades
            for (String carrera : CtrlCarrera.listar()) {
                this.jCmbCarreraSemi.addItem(carrera);
            }//Fin de for

            //2. Cargar la lista de departamentos
            //for (negocio.Tutor tut : CtrlTutor.listar()) {
            //    this.jCmbTutorSemi.addItem(tut.getNombre() + " " + tut.getP_apellido());
            //}//Fin for departamentos            
        } catch (ClassNotFoundException | InstantiationException
                | IllegalAccessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Se ha producido una falla"
                    + " al tratar de listar Facultades y Departamentos \n "
                    + " registrados actualmente", "Error al cargar"
                    + "listado", JOptionPane.ERROR_MESSAGE);
        }//Fin
    }//GEN-LAST:event_formInternalFrameActivated

    private void jBtnExaminarSemiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExaminarSemiActionPerformed
        // Crear un diálogo para seleccionar el archivo PDF         
        JFileChooser jf = new JFileChooser();
        jf.setDialogTitle("Seleccionar el resumen del Seminario");
        jf.setApproveButtonText("Aceptar");
        jf.setMultiSelectionEnabled(false);
        jf.setFileFilter(new FileNameExtensionFilter("Seleccionar pdf", "pdf"));
        int result = jf.showOpenDialog(this);

        //Indicar si se ha aprovado la elección de algun elemento
        if (result == JFileChooser.APPROVE_OPTION) {
            //Obtener el archivo seleccionado
            File selectedFile = jf.getSelectedFile();
            // Directorio de destino para guardar el archivo
            String destino = System.getProperty("user.dir") + "\\Seminarios\\";
            try {
                // Copiar el archivo PDF al directorio de destino
                Path rutaOrg = selectedFile.toPath();
                Path destinoPath = Path.of(destino, selectedFile.getName());
                Files.copy(rutaOrg, destinoPath, StandardCopyOption.REPLACE_EXISTING);
                this.jTxtResumenSemi.setText(destino + selectedFile.getName());
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error, no es posible "
                        + "realizar la acción \n para corregir prueba algunas"
                        + "de las siguientes opciones:\n "
                        + "1. El path al directorio destino exista \n"
                        + "2. Ha seleccionado un archivo con formato valido"
                        + e.getMessage(), "Error al Operar", JOptionPane.ERROR_MESSAGE);
            }
        }//Fin
    }//GEN-LAST:event_jBtnExaminarSemiActionPerformed

    private void jCmbCarreraSemiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbCarreraSemiItemStateChanged
        // Recuperar el ID de la carrera seleccionada
        try {
            String item = "";
            if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
                item = (String) jCmbCarreraSemi.getSelectedItem();
            }
            //Buscar y asignar el id correspondiente del departamento 
            idCarrera = CtrlCarrera.recuperarIdCarrera(item);
        } catch (ClassNotFoundException | InstantiationException
                | IllegalAccessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Se ha producido un \n "
                    + " error al intentar recuperar identificador " + ex.getMessage(),
                    "Registro no encontrado", JOptionPane.ERROR_MESSAGE);
        }//Fin
    }//GEN-LAST:event_jCmbCarreraSemiItemStateChanged

    private void jBtnBuscarTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarTutorActionPerformed
        // Buscar Tutor mediante un INSS
        String inss = JOptionPane.showInputDialog(this, "Digite "
                + "número de INSS del tutor",
                "Tutor a Buscar", JOptionPane.INFORMATION_MESSAGE);
        //Buscar el Tutor de acuerdo al corre electrónco especificado
        try {
            negocio.Tutor t = CtrlTutor.leerRegistro(inss);
            if (t != null) {
                //Recuperar el Id que se mandará a relacionar
                idTutor = t.getIdTut();
                this.jTxtTutorNombre.setText(t.getNombre() + " " + t.getP_apellido()
                        + " " + t.getS_apellido());
            }

        } catch (ClassNotFoundException | InstantiationException
                | IllegalAccessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "No se ha podido"
                    + " identificar al tutor \n " + ex.getMessage()
                    + " indicado por número de INSS",
                    "Registro no encontrado"
                    + "listado", JOptionPane.ERROR_MESSAGE);
        }//Fin
    }//GEN-LAST:event_jBtnBuscarTutorActionPerformed

    private void jTxtTutorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTutorNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTutorNombreActionPerformed

    private void jBtnGuardarSemiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarSemiActionPerformed
        // Guardar un seminario
        try {
            if (!validateForm()) {
                JOptionPane.showMessageDialog(null, "Por favor, rellene todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                Date d = jDtChFechaSeminario.getDate();
                System.out.println(d);
                SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                String fechaFormateada = format.format(d);
                System.out.println(fechaFormateada);
                
                // Preparar los datos que se guardaran del Tutor
                int ans = CtrlSeminario.insertar_seminario(
                        this.jTxtTemaSemi.getText(),
                        this.jTxtResumenSemi.getText(),
                        fechaFormateada,
                        //this.jDtChFechaSeminario.getDate().toString(),
                        this.idEst_1,
                        this.idEst_2,
                        this.idEst_3,
                        this.idTutor,
                        this.idCarrera,
                        Integer.parseInt(jCmbSemestreSemi.getSelectedItem().toString()));

                // Validamos si se guardo el registro
                if (ans > 0) {
                    JOptionPane.showMessageDialog(this, "Registro grabado con exito",
                            "Grabar Registro", JOptionPane.INFORMATION_MESSAGE);
                    //this.clearForm(); //Limpiar los campos del formulario
                    //this.limpiar();
                }//Fin de la instrucción if
            }

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error al intentar guardar "
                    + "el \n registro, no se encuentra una librería",
                    "Librería no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (InstantiationException ex) {
            JOptionPane.showMessageDialog(this, "Se ha producido una falla al "
                    + "hacer referencia \n de una instancia",
                    "Instancia no Encontrada", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalAccessException ex) {
            JOptionPane.showMessageDialog(this, "Se ha denegado el acceso al  "
                    + "intentar utilizar \n la librería o instancia para guardar",
                    "Acceso Ilegal a un Recurso", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Se ha producido una falla con "
                    + "el manejo de la solicitud \n al intentar registrar datos "
                    + "\n" + ex.getMessage(),
                    "Error al Procesar Datos", JOptionPane.ERROR_MESSAGE);
        }//Fin
    }//GEN-LAST:event_jBtnGuardarSemiActionPerformed

    // Validar los campos del formulario
    private boolean validateForm(){
        boolean ans = true;
        
        if(jTxtTutorNombre.getText().isBlank()
                || jCmbCarreraSemi.getSelectedItem() == "Seleccione"
                || jCmbSemestreSemi.getSelectedItem() == "Seleccione"
                || jTxtAutor1Semi.getText().isBlank()
                || jTxtTemaSemi.getText().isBlank()
                || jTxtResumenSemi.getText().isBlank()
                || jDtChFechaSeminario.getDate().toString().isBlank()){
            
            ans = false;
        }
        
        return ans;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBorrarSemi;
    private javax.swing.JButton jBtnBuscarAutSemi1;
    private javax.swing.JButton jBtnBuscarAutSemi2;
    private javax.swing.JButton jBtnBuscarAutSemi3;
    private javax.swing.JButton jBtnBuscarTutor;
    private javax.swing.JButton jBtnExaminarSemi;
    private javax.swing.JButton jBtnGuardarSemi;
    private javax.swing.JComboBox<String> jCmbCarreraSemi;
    private javax.swing.JComboBox<String> jCmbSemestreSemi;
    private com.toedter.calendar.JDateChooser jDtChFechaSeminario;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTxtAutor1Semi;
    private javax.swing.JTextField jTxtAutor2Semi;
    private javax.swing.JTextField jTxtAutor3Semi;
    private javax.swing.JTextField jTxtResumenSemi;
    private javax.swing.JTextField jTxtTemaSemi;
    private javax.swing.JTextField jTxtTutorNombre;
    // End of variables declaration//GEN-END:variables
}
