package ui;

import datos.ImagenFondo;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class Sistema_UI extends javax.swing.JFrame {

    //negocio.Usuario user;
    //protected int idUsuaroActual;
    public Sistema_UI() throws IOException {
        initComponents();
        //user = new negocio.Usuario();
        //this.idUsuaroActual = 0;
        dskPanelMDI.setBorder(new ImagenFondo());
        //Maximizar la ventana de inicio
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        dskPanelMDI = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        jItemCatalogo = new javax.swing.JMenu();
        Tutor = new javax.swing.JMenuItem();
        Evaluador = new javax.swing.JMenuItem();
        Estudiante = new javax.swing.JMenuItem();
        Empleado = new javax.swing.JMenuItem();
        jMnuEstatico = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jitemGuardar = new javax.swing.JMenu();
        itemProtocolo = new javax.swing.JMenuItem();
        itemTesis = new javax.swing.JMenuItem();
        Seminario = new javax.swing.JMenuItem();
        itemTesisMaestria = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        ItemConsulta = new javax.swing.JMenuItem();
        jMenuReportes = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jmnu_Configuracion = new javax.swing.JMenu();
        jSep_BaseDatos = new javax.swing.JPopupMenu.Separator();
        jItem_ConfDB = new javax.swing.JMenuItem();
        jMnu_Sesion = new javax.swing.JMenu();
        jItem_Exit = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMnuInicioSesion = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout dskPanelMDILayout = new javax.swing.GroupLayout(dskPanelMDI);
        dskPanelMDI.setLayout(dskPanelMDILayout);
        dskPanelMDILayout.setHorizontalGroup(
            dskPanelMDILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );
        dskPanelMDILayout.setVerticalGroup(
            dskPanelMDILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        menuBar.setBackground(new java.awt.Color(153, 153, 153));

        jItemCatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/catalogo.png"))); // NOI18N
        jItemCatalogo.setMnemonic('f');
        jItemCatalogo.setText("Catálogo");
        jItemCatalogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jItemCatalogo.setEnabled(false);

        Tutor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Tutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tutor.png"))); // NOI18N
        Tutor.setMnemonic('o');
        Tutor.setText("Tutor");
        Tutor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TutorActionPerformed(evt);
            }
        });
        jItemCatalogo.add(Tutor);

        Evaluador.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Evaluador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/evaluar.png"))); // NOI18N
        Evaluador.setMnemonic('s');
        Evaluador.setText("Evaluador");
        Evaluador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Evaluador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EvaluadorActionPerformed(evt);
            }
        });
        jItemCatalogo.add(Evaluador);

        Estudiante.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Estudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/graduated.png"))); // NOI18N
        Estudiante.setText("Estudiante");
        Estudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Estudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudianteActionPerformed(evt);
            }
        });
        jItemCatalogo.add(Estudiante);

        Empleado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/division.png"))); // NOI18N
        Empleado.setText("Empleado");
        Empleado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadoActionPerformed(evt);
            }
        });
        jItemCatalogo.add(Empleado);

        jMnuEstatico.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMnuEstatico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exam.png"))); // NOI18N
        jMnuEstatico.setText("Carrera");
        jMnuEstatico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMnuEstatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuEstaticoActionPerformed(evt);
            }
        });
        jItemCatalogo.add(jMnuEstatico);

        jMenuItem3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/education.png"))); // NOI18N
        jMenuItem3.setText("Modalidad de graduación");
        jMenuItem3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jItemCatalogo.add(jMenuItem3);

        menuBar.add(jItemCatalogo);

        jitemGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/verify.png"))); // NOI18N
        jitemGuardar.setMnemonic('e');
        jitemGuardar.setText("Registros");
        jitemGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jitemGuardar.setEnabled(false);
        jitemGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jitemGuardarMouseClicked(evt);
            }
        });

        itemProtocolo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        itemProtocolo.setMnemonic('t');
        itemProtocolo.setText("Protocolo");
        itemProtocolo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemProtocolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProtocoloActionPerformed(evt);
            }
        });
        jitemGuardar.add(itemProtocolo);

        itemTesis.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        itemTesis.setMnemonic('y');
        itemTesis.setText("Monografia");
        itemTesis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemTesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTesisActionPerformed(evt);
            }
        });
        jitemGuardar.add(itemTesis);

        Seminario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Seminario.setMnemonic('p');
        Seminario.setText("Seminario");
        Seminario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Seminario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeminarioActionPerformed(evt);
            }
        });
        jitemGuardar.add(Seminario);

        itemTesisMaestria.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        itemTesisMaestria.setText("Tesis");
        itemTesisMaestria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemTesisMaestria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTesisMaestriaActionPerformed(evt);
            }
        });
        jitemGuardar.add(itemTesisMaestria);

        menuBar.add(jitemGuardar);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/a-la-vista.png"))); // NOI18N
        jMenu1.setText("Consultas");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        ItemConsulta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ItemConsulta.setText("Consulta");
        ItemConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ItemConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemConsultaActionPerformed(evt);
            }
        });
        jMenu1.add(ItemConsulta);

        menuBar.add(jMenu1);

        jMenuReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reporte.png"))); // NOI18N
        jMenuReportes.setText("Reportes ");
        jMenuReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuReportes.setEnabled(false);

        jMenuItem8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem8.setText("Seminarios por carrera");
        jMenuItem8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenuReportes.add(jMenuItem8);

        jMenuItem6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem6.setText("Protocolos por semestres");
        jMenuItem6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuReportes.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem7.setText("Protocolos por carrera");
        jMenuItem7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenuReportes.add(jMenuItem7);

        jMenuItem9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem9.setText("Tesis monográficas inscritas por carrera");
        jMenuItem9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenuReportes.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem10.setText("Tutorias");
        jMenuItem10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenuReportes.add(jMenuItem10);

        menuBar.add(jMenuReportes);

        jmnu_Configuracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/settings.png"))); // NOI18N
        jmnu_Configuracion.setText("Configuración");
        jmnu_Configuracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jmnu_Configuracion.setEnabled(false);
        jmnu_Configuracion.add(jSep_BaseDatos);

        jItem_ConfDB.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jItem_ConfDB.setText("Configurar Base de Datos");
        jItem_ConfDB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jItem_ConfDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItem_ConfDBActionPerformed(evt);
            }
        });
        jmnu_Configuracion.add(jItem_ConfDB);

        menuBar.add(jmnu_Configuracion);

        jMnu_Sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cerrar-sesion.png"))); // NOI18N
        jMnu_Sesion.setText("Sesión");
        jMnu_Sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jItem_Exit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jItem_Exit.setText("Cerrar Sistema");
        jItem_Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jItem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItem_ExitActionPerformed(evt);
            }
        });
        jMnu_Sesion.add(jItem_Exit);

        jMenuItem5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMenuItem5.setText("Usuario");
        jMenuItem5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMnu_Sesion.add(jMenuItem5);

        jMnuInicioSesion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMnuInicioSesion.setText("Iniciar sesión");
        jMnuInicioSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMnuInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuInicioSesionActionPerformed(evt);
            }
        });
        jMnu_Sesion.add(jMnuInicioSesion);

        menuBar.add(jMnu_Sesion);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPanelMDI)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPanelMDI, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jItem_ConfDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItem_ConfDBActionPerformed
        // TODO add your handling code here:
        Conf_Server config = new Conf_Server();
        this.dskPanelMDI.add(config);
        config.show();
    }//GEN-LAST:event_jItem_ConfDBActionPerformed

    private void jItem_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItem_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jItem_ExitActionPerformed

    private void EvaluadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EvaluadorActionPerformed

        Evaluador nuevoEvaluador;
        nuevoEvaluador = new Evaluador(); //Crear la instancia
        nuevoEvaluador.setLocation(120, 100);//indica las coordenadas donde se ubicara el frm
        this.dskPanelMDI.add(nuevoEvaluador); //Agregar al Panel
        nuevoEvaluador.show(); //Mostrar el formulario

    }//GEN-LAST:event_EvaluadorActionPerformed

    private void SeminarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeminarioActionPerformed
        Seminario nuevoSemi;
        nuevoSemi = new Seminario(); //Crear la instancia
        nuevoSemi.setLocation(35, 85);//indica las coordenadas donde se ubicara el frm
        this.dskPanelMDI.add(nuevoSemi); //Agregar al Panel
        nuevoSemi.show(); //Mostrar el formulario
    }//GEN-LAST:event_SeminarioActionPerformed

    private void itemTesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTesisActionPerformed
        Tesis_Monografica nuevoGrado;
        nuevoGrado = new Tesis_Monografica(); //Crear la instancia
        nuevoGrado.setLocation(8, 85);//indica las coordenadas donde se ubicara el frm
        this.dskPanelMDI.add(nuevoGrado); //Agregar al Panel
        nuevoGrado.show(); //Mostrar el formulario
    }//GEN-LAST:event_itemTesisActionPerformed

    private void itemProtocoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProtocoloActionPerformed
        // TODO add your handling code here:
        Protocolo nuevoProtocolo;
        nuevoProtocolo = new Protocolo(); //Crear la instancia
        nuevoProtocolo.setLocation(45, 85);//indica las coordenadas donde se ubicara el frm
        this.dskPanelMDI.add(nuevoProtocolo); //Agregar al Panel
        nuevoProtocolo.show(); //Mostrar el formulario


    }//GEN-LAST:event_itemProtocoloActionPerformed

    private void TutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutorActionPerformed

        Tutor nuevoTutor;
        nuevoTutor = new Tutor(); //Crear la instancia
        nuevoTutor.setLocation(120, 100); //indica las coordenadas donde se ubicara el frm
        this.dskPanelMDI.add(nuevoTutor); //Agregar al Panel
        nuevoTutor.show(); //Mostrar el formulario

    }//GEN-LAST:event_TutorActionPerformed

    private void itemTesisMaestriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTesisMaestriaActionPerformed
        Tesis_Maestria nuevaMaestria;
        nuevaMaestria = new Tesis_Maestria(); //Crear la instancia
        nuevaMaestria.setLocation(90, 100);//indica las coordenadas donde se ubicara el frm
        this.dskPanelMDI.add(nuevaMaestria); //Agregar al Panel
        nuevaMaestria.show(); //Mostrar el formulario


    }//GEN-LAST:event_itemTesisMaestriaActionPerformed

    private void jitemGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jitemGuardarMouseClicked

    }//GEN-LAST:event_jitemGuardarMouseClicked

    private void EstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudianteActionPerformed
        Estudiante nuevoEstu;
        nuevoEstu = new Estudiante(); //Crear la instancia
        nuevoEstu.setLocation(120, 100);//indica las coordenadas donde se ubicara el frm
        this.dskPanelMDI.add(nuevoEstu); //Agregar al Panel
        nuevoEstu.show(); //Mostrar el formulario   
    }//GEN-LAST:event_EstudianteActionPerformed

    private void EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadoActionPerformed
        Empleado nuevoEmp;
        nuevoEmp = new Empleado(); //Crear la instancia
        nuevoEmp.setLocation(120, 100);//indica las coordenadas donde se ubicara el frm
        this.dskPanelMDI.add(nuevoEmp); //Agregar al Panel
        nuevoEmp.show(); //Mostrar el formulario

    }//GEN-LAST:event_EmpleadoActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed


    }//GEN-LAST:event_jMenu1ActionPerformed

    private void ItemConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemConsultaActionPerformed
        // TODO add your handling code here:
        Consultas nuevoConsulta;
        nuevoConsulta = new Consultas(); //Crear la instancia
        nuevoConsulta.setLocation(25, 45);//indica las coordenadas donde se ubicara el frm
        this.dskPanelMDI.add(nuevoConsulta); //Agregar al Panel
        nuevoConsulta.show(); //Mostrar el formulario
    }//GEN-LAST:event_ItemConsultaActionPerformed

    private void jMnuEstaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuEstaticoActionPerformed
        // TODO add your handling code here:
        Carrera nuevoCarrera;
        nuevoCarrera = new Carrera(); //Crear la instancia
        nuevoCarrera.setLocation(5, 0);//indica las coordenadas donde se ubicara el frm
        this.dskPanelMDI.add(nuevoCarrera); //Agregar al Panel
        nuevoCarrera.show(); //Mostrar el formulario
    }//GEN-LAST:event_jMnuEstaticoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        ModalidadGraduacion nuevaMod;
        nuevaMod = new ModalidadGraduacion(); //Crear la instancia
        nuevaMod.setLocation(5, 0);//indica las coordenadas donde se ubicara el frm
        this.dskPanelMDI.add(nuevaMod); //Agregar al Panel
        nuevaMod.show(); //Mostrar el formulario
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        ui.Usuario nuevoUser;
        nuevoUser = new ui.Usuario(); //Crear la instancia
        nuevoUser.setLocation(50, 50);//indica las coordenadas donde se ubicara el frm
        this.dskPanelMDI.add(nuevoUser); //Agregar al Panel
        nuevoUser.show(); //Mostrar el formulario
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMnuInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuInicioSesionActionPerformed
        if (Sistema_UI.jMnuInicioSesion.getText().equals("Cerrar sesión")) {
            negocio.Usuario user = negocio.Usuario.getInstance();
            user.setIdUser(0);
            user.setIdEmpleado(0);
            user.setCorreo("");
            user.setContrasenia("");
            jmnu_Configuracion.setEnabled(false);
            jMenuReportes.setEnabled(false);
            jItemCatalogo.setEnabled(false);
            jitemGuardar.setEnabled(false);
            jMnuInicioSesion.setText("Iniciar sesión");

        } else {
            Login nuevoLogin;
            nuevoLogin = new Login(); //Crear la instancia
            nuevoLogin.setLocation(50, 50);//indica las coordenadas donde se ubicara el frm
            this.dskPanelMDI.add(nuevoLogin); //Agregar al Panel
            nuevoLogin.show(); //Mostrar el formulario
        }

    }//GEN-LAST:event_jMnuInicioSesionActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ReporteSemestre nuevoSemestre;
        nuevoSemestre = new ReporteSemestre(); //Crear la instancia
        nuevoSemestre.setLocation(175, 30);//indica las coordenadas donde se ubicara el frm
        this.dskPanelMDI.add(nuevoSemestre); //Agregar al Panel
        nuevoSemestre.show(); //Mostrar el formulario
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        ReporteGrado nuevogrado;
        nuevogrado = new ReporteGrado(); //Crear la instancia
        nuevogrado.setLocation(175, 30);//indica las coordenadas donde se ubicara el frm
        this.dskPanelMDI.add(nuevogrado); //Agregar al Panel
        nuevogrado.show(); //Mostrar el formulario
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        ReporteCarrera nuevoCarrera;
        nuevoCarrera = new ReporteCarrera(); //Crear la instancia
        nuevoCarrera.setLocation(175, 30);//indica las coordenadas donde se ubicara el frm
        this.dskPanelMDI.add(nuevoCarrera); //Agregar al Panel
        nuevoCarrera.show(); //Mostrar el formulario
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        ReporteMonografia nuevoMono;
        nuevoMono = new ReporteMonografia(); //Crear la instancia
        nuevoMono.setLocation(175, 30);//indica las coordenadas donde se ubicara el frm
        this.dskPanelMDI.add(nuevoMono); //Agregar al Panel
        nuevoMono.show(); //Mostrar el formulario
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        ReporteTutor nuevoTutor;
        nuevoTutor = new ReporteTutor(); //Crear la instancia
        nuevoTutor.setLocation(175, 30);//indica las coordenadas donde se ubicara el frm
        this.dskPanelMDI.add(nuevoTutor); //Agregar al Panel
        nuevoTutor.show(); //Mostrar el formulario
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    public void InicioSesionVerificacion() {
        negocio.Usuario user = negocio.Usuario.getInstance();
        try {
            ///int idUsuaroActual = user.getIdUser();

            System.out.println(user.getIdUser());

            if (user.getIdUser() != 0) {
                jItemCatalogo.setEnabled(true);
            }

        } catch (Exception error) {

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Sistema_UI().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Sistema_UI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        //Preparar la carga de archivos de configuración
        try {

            FileInputStream fis = new FileInputStream(System.getProperty(
                    "user.dir") + "\\src\\servicios\\config.txt");
            Properties p = new Properties(System.getProperties());
            p.load(fis);
            System.setProperties(p);
        } catch (java.io.FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Archivo de Configuración"
                    + " de acceso a datos \n no encontrado, revisar configuración",
                    "Configuración de acceso", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }//Fin de la instrucción catch
        catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error en lectura de datos "
                    + "de inicio de configuración   \n",
                    "Error al leer configuración",
                    JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }//Fin catch)

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Empleado;
    private javax.swing.JMenuItem Estudiante;
    private javax.swing.JMenuItem Evaluador;
    private javax.swing.JMenuItem ItemConsulta;
    private javax.swing.JMenuItem Seminario;
    private javax.swing.JMenuItem Tutor;
    public static javax.swing.JDesktopPane dskPanelMDI;
    private javax.swing.JMenuItem itemProtocolo;
    private javax.swing.JMenuItem itemTesis;
    private javax.swing.JMenuItem itemTesisMaestria;
    public static javax.swing.JMenu jItemCatalogo;
    private javax.swing.JMenuItem jItem_ConfDB;
    private javax.swing.JMenuItem jItem_Exit;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    public static javax.swing.JMenu jMenuReportes;
    private javax.swing.JMenuItem jMnuEstatico;
    public static javax.swing.JMenuItem jMnuInicioSesion;
    private javax.swing.JMenu jMnu_Sesion;
    private javax.swing.JPopupMenu.Separator jSep_BaseDatos;
    public static javax.swing.JMenu jitemGuardar;
    public static javax.swing.JMenu jmnu_Configuracion;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
